Generating a tree for: izaya@social.shadowkat.net
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 140, in <module>
    accounts = get_accounts(accounts_ids, external_api)
  File "/home/mastodon/mastoes-bots/feditree.py", line 52, in get_accounts
    account = _api.account(accounts_ids[i])
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 128, in account
    return self.__api_request('GET', url)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', "Can't find user")

External api failed, using internal api instead.
Generating a tree for: maciek33@pol.social
Generating a tree for: slatian@pleroma.envs.net
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 140, in <module>
    accounts = get_accounts(accounts_ids, external_api)
  File "/home/mastodon/mastoes-bots/feditree.py", line 52, in get_accounts
    account = _api.account(accounts_ids[i])
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 128, in account
    return self.__api_request('GET', url)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', "Can't find user")

External api failed, using internal api instead.
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 156, in <module>
    if omitted_accounts > 0:
TypeError: '>' not supported between instances of 'AttribAccessDict' and 'int'

Generating a tree for: slatian@pleroma.envs.net
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 140, in <module>
    accounts = get_accounts(accounts_ids, external_api)
  File "/home/mastodon/mastoes-bots/feditree.py", line 52, in get_accounts
    account = _api.account(accounts_ids[i])
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 128, in account
    return self.__api_request('GET', url)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', "Can't find user")

External api failed, using internal api instead.
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 156, in <module>
    if omitted_accounts > 0:
TypeError: '>' not supported between instances of 'AttribAccessDict' and 'int'

Skipping generation, a tree was already generated for: blaues_gummibaer@friendica.opensocial.space
Generating a tree for: Mateusz@101010.pl
Skipping generation, a tree was already generated for: owashe@meow.social
Generating a tree for: ruxotves@hed.im
Generating a tree for: cichy1173@mastodon.social
Generating a tree for: raccoonformality@tech.lgbt
Generating a tree for: paper_modeler@101010.pl
Generating a tree for: 46and2@social.tchncs.de
Skipping generation, a tree was already generated for: owashe@meow.social
Generating a tree for: owashe@meow.social
Generating a tree for: revu@xarxa.cloud
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 154, in <module>
    image = create_image(accounts)
  File "/home/mastodon/mastoes-bots/feditree.py", line 84, in create_image
    with Image.open('feditree/avatar.png') as avatar:
  File "/home/mastodon/.local/lib/python3.9/site-packages/PIL/Image.py", line 3536, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/home/mastodon/mastoes-bots/feditree/avatar.png'

Generating a tree for: Bilchi@nrw.social
Generating a tree for: atwm@mastodon.social
Generating a tree for: kimlockhartga@beige.party
Generating a tree for: snow@thefurpack.eu
Traceback (most recent call last):
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 306, in __api_request
    response = response_object.json(object_hook=self.__json_hooks)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 308, in __api_request
    raise MastodonAPIError(
mastodon.errors.MastodonAPIError: Could not parse response as JSON, response code was 200, bad json content was 'b'<!DOCTYPE html>\n<html  >\n<head>\n  \n  <meta charset="UTF-8">\n  <meta http-equiv="X-UA-Compatible" content="IE=edge">\n  \n  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">\n  <link rel="shortcut icon" href="assets/images/bobbybui-1.png" type="image/x-icon">\n  <meta name="description" content="">\n  \n  \n  <title>Home</title>\n  <link rel="stylesheet" href="assets/web/assets/mobirise-icons2/mobirise2.css">\n  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">\n  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap-grid.min.css">\n  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap-reboot.min.css">\n  <link rel="stylesheet" href="assets/dropdown/css/style.css">\n  <link rel="stylesheet" href="assets/theme/css/style.css">\n  <link rel="preload" href="https://fonts.googleapis.com/css?family=Inter+Tight:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap" as="style" onload="this.onload=null;this.rel=\'stylesheet\'">\n  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter+Tight:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap"></noscript>\n  <link rel="preload" as="style" href="assets/mobirise/css/mbr-additional.css?v=3bVzLj"><link rel="stylesheet" href="assets/mobirise/css/mbr-additional.css?v=3bVzLj" type="text/css">\n\n  \n  \n  \n</head>\n<body>\n  \n  <section data-bs-version="5.1" class="menu menu1 cid-uv57SmAmzQ" once="menu" id="menu01-0">\n\t\n\n\t<nav class="navbar navbar-dropdown navbar-expand-lg">\n\t\t<div class="container">\n\t\t\t<div class="navbar-brand">\n\t\t\t\t<span class="navbar-logo">\n\t\t\t\t\t\n\t\t\t\t\t\t<img src="assets/images/bobbybui-1.png" alt="The fur pack logo" style="height: 3.5rem;">\n\t\t\t\t\t\n\t\t\t\t</span>\n\t\t\t\t<span class="navbar-caption-wrap"><a class="navbar-caption text-white text-primary display-4">The fur pack</a></span>\n\t\t\t</div>\n\t\t\t<button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbarSupportedContent" data-bs-target="#navbarSupportedContent" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">\n\t\t\t\t<div class="hamburger">\n\t\t\t\t\t<span></span>\n\t\t\t\t\t<span></span>\n\t\t\t\t\t<span></span>\n\t\t\t\t\t<span></span>\n\t\t\t\t</div>\n\t\t\t</button>\n\t\t\t<div class="collapse navbar-collapse" id="navbarSupportedContent">\n\t\t\t\t<ul class="navbar-nav nav-dropdown" data-app-modern-menu="true"><li class="nav-item">\n\t\t\t\t\t\t<a class="nav-link link text-white display-4" href="https://thefurpack.eu"></a>\n\t\t\t\t\t</li></ul>\n\t\t\t\t\n\t\t\t\t<div class="navbar-buttons mbr-section-btn"><a class="btn btn-white-outline display-4" href="https://hub.thefurpack.eu">Mastodon</a></div>\n\t\t\t</div>\n\t\t</div>\n\t</nav>\n</section>\n\n<section data-bs-version="5.1" class="article07 cid-uv5cY7Ul1w" id="article07-2">\n  \n\n  \n  \n  <div class="container">\n    <div class="row justify-content-center">\n      <div class="card col-md-12 col-lg-10">\n        <div class="card-wrapper">\n          <h3 class="card-title mbr-fonts-style mbr-white mt-3 mb-4 display-2"></h3>\n          <div class="row card-box align-left">\n            <div class="item features-without-image col-12">\n              <div class="item-wrapper">\n                <h4 class="mbr-section-subtitle mbr-fonts-style mb-3 display-2">The fur pack mastodon server</h4>\n                <p class="mbr-text mbr-fonts-style display-7">The fur pack is a mastodon server that is meant to be a safe space for furs that are apart of the LGBTQ+ community. We are a welcoming community to anybody that wants to join. You don\'t have to be a furry or apart of the LGBTQ+ community to join</p>\n              </div>\n            </div>\n            \n            \n            \n          </div>\n          \n        </div>\n      </div>\n    </div>\n  </div>\n</section>\n\n<section class="mbr-section mbr-section--no-padding cid-uv8b0FlqIR" id="witsec-html-block-5">\n\n\n\n\n\n<!-- Place your own code below -->\n<center>\n<blockquote class="mastodon-embed" data-embed-url="https://hub.thefurpack.eu/@snow/113438726807285991/embed" style="background: #FCF8FF; border-radius: 8px; border: 1px solid #C9C4DA; margin: 0; max-width: 540px; min-width: 270px; overflow: hidden; padding: 0;"> <a href="https://hub.thefurpack.eu/@snow/113438726807285991" target="_blank" style="align-items: center; color: #1C1A25; display: flex; flex-direction: column; font-family: system-ui, -apple-system, BlinkMacSystemFont, \'Segoe UI\', Oxygen, Ubuntu, Cantarell, \'Fira Sans\', \'Droid Sans\', \'Helvetica Neue\', Roboto, sans-serif; font-size: 14px; justify-content: center; letter-spacing: 0.25px; line-height: 20px; padding: 24px; text-decoration: none;"> <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="32" height="32" viewBox="0 0 79 75"><path d="M74.7135 16.6043C73.6199 8.54587 66.5351 2.19527 58.1366 0.964691C56.7196 0.756754 51.351 0 38.9148 0H38.822C26.3824 0 23.7135 0.756754 22.2966 0.964691C14.1319 2.16118 6.67571 7.86752 4.86669 16.0214C3.99657 20.0369 3.90371 24.4888 4.06535 28.5726C4.29578 34.4289 4.34049 40.275 4.877 46.1075C5.24791 49.9817 5.89495 53.8251 6.81328 57.6088C8.53288 64.5968 15.4938 70.4122 22.3138 72.7848C29.6155 75.259 37.468 75.6697 44.9919 73.971C45.8196 73.7801 46.6381 73.5586 47.4475 73.3063C49.2737 72.7302 51.4164 72.086 52.9915 70.9542C53.0131 70.9384 53.0308 70.9178 53.0433 70.8942C53.0558 70.8706 53.0628 70.8445 53.0637 70.8179V65.1661C53.0634 65.1412 53.0574 65.1167 53.0462 65.0944C53.035 65.0721 53.0189 65.0525 52.9992 65.0371C52.9794 65.0218 52.9564 65.011 52.9318 65.0056C52.9073 65.0002 52.8819 65.0003 52.8574 65.0059C48.0369 66.1472 43.0971 66.7193 38.141 66.7103C29.6118 66.7103 27.3178 62.6981 26.6609 61.0278C26.1329 59.5842 25.7976 58.0784 25.6636 56.5486C25.6622 56.5229 25.667 56.4973 25.6775 56.4738C25.688 56.4502 25.7039 56.4295 25.724 56.4132C25.7441 56.397 25.7678 56.3856 25.7931 56.3801C25.8185 56.3746 25.8448 56.3751 25.8699 56.3816C30.6101 57.5151 35.4693 58.0873 40.3455 58.086C41.5183 58.086 42.6876 58.086 43.8604 58.0553C48.7647 57.919 53.9339 57.6701 58.7591 56.7361C58.8794 56.7123 58.9998 56.6918 59.103 56.6611C66.7139 55.2124 73.9569 50.665 74.6929 39.1501C74.7204 38.6967 74.7892 34.4016 74.7892 33.9312C74.7926 32.3325 75.3085 22.5901 74.7135 16.6043ZM62.9996 45.3371H54.9966V25.9069C54.9966 21.8163 53.277 19.7302 49.7793 19.7302C45.9343 19.7302 44.0083 22.1981 44.0083 27.0727V37.7082H36.0534V27.0727C36.0534 22.1981 34.124 19.7302 30.279 19.7302C26.8019 19.7302 25.0651 21.8163 25.0617 25.9069V45.3371H17.0656V25.3172C17.0656 21.2266 18.1191 17.9769 20.2262 15.568C22.3998 13.1648 25.2509 11.9308 28.7898 11.9308C32.8859 11.9308 35.9812 13.492 38.0447 16.6111L40.036 19.9245L42.0308 16.6111C44.0943 13.492 47.1896 11.9308 51.2788 11.9308C54.8143 11.9308 57.6654 13.1648 59.8459 15.568C61.9529 17.9746 63.0065 21.2243 63.0065 25.3172L62.9996 45.3371Z" fill="currentColor"></path></svg> <div style="color: #787588; margin-top: 16px;">Post by @<span class="__cf_email__" data-cfemail="f3809d9c84b3879b9695868183929098dd9686">[email&#160;protected]</span></div> <div style="font-weight: 500;">View on Mastodon</div> </a> </blockquote> <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script data-allowed-prefixes="https://hub.thefurpack.eu/" async src="https://hub.thefurpack.eu/embed.js"></script>\n</center>\n<!-- Place your own code above -->\n\n</section>\n\n<section data-bs-version="5.1" class="article07 cid-uv5sFlf89k" id="article07-4">\n  \n\n  \n  \n  <div class="container">\n    <div class="row justify-content-center">\n      <div class="card col-md-12 col-lg-10">\n        <div class="card-wrapper">\n          <h3 class="card-title mbr-fonts-style mbr-white mt-3 mb-4 display-2"></h3>\n          <div class="row card-box align-left">\n            <div class="item features-without-image col-12">\n              <div class="item-wrapper">\n                <h4 class="mbr-section-subtitle mbr-fonts-style mb-3 display-2"></h4>\n                <p class="mbr-text mbr-fonts-style display-7"></p>\n              </div>\n            </div>\n            \n            \n            \n          </div>\n          \n        </div>\n      </div>\n    </div>\n  </div>\n</section><section><a href="https://mobiri.se"></a><a href="https://mobiri.se"></a></section><script src="assets/bootstrap/js/bootstrap.bundle.min.js"></script>  <script src="assets/smoothscroll/smooth-scroll.js"></script>  <script src="assets/ytplayer/index.js"></script>  <script src="assets/dropdown/js/navbar-dropdown.js"></script>  <script src="assets/theme/js/script.js"></script>  \n  \n  \n</body>\n</html>''

External api failed, using internal api instead.
Skipping generation, a tree was already generated for: Weinberg@mastodon.social
Generating a tree for: RossGayler@aus.social
Generating a tree for: Andreas@kirche.social
Generating a tree for: slirt@weird.autos
Generating a tree for: vitriolix@mastodon.social
Skipping generation, a tree was already generated for: Weinberg@mastodon.social
Generating a tree for: mondanzo@wolfdo.gg
Generating a tree for: snow@thefurpack.eu
Traceback (most recent call last):
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 306, in __api_request
    response = response_object.json(object_hook=self.__json_hooks)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 308, in __api_request
    raise MastodonAPIError(
mastodon.errors.MastodonAPIError: Could not parse response as JSON, response code was 200, bad json content was 'b'<!DOCTYPE html>\n<html  >\n<head>\n  \n  <meta charset="UTF-8">\n  <meta http-equiv="X-UA-Compatible" content="IE=edge">\n  \n  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">\n  <link rel="shortcut icon" href="assets/images/bobbybui-1.png" type="image/x-icon">\n  <meta name="description" content="">\n  \n  \n  <title>Home</title>\n  <link rel="stylesheet" href="assets/web/assets/mobirise-icons2/mobirise2.css">\n  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">\n  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap-grid.min.css">\n  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap-reboot.min.css">\n  <link rel="stylesheet" href="assets/dropdown/css/style.css">\n  <link rel="stylesheet" href="assets/theme/css/style.css">\n  <link rel="preload" href="https://fonts.googleapis.com/css?family=Inter+Tight:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap" as="style" onload="this.onload=null;this.rel=\'stylesheet\'">\n  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter+Tight:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap"></noscript>\n  <link rel="preload" as="style" href="assets/mobirise/css/mbr-additional.css?v=3bVzLj"><link rel="stylesheet" href="assets/mobirise/css/mbr-additional.css?v=3bVzLj" type="text/css">\n\n  \n  \n  \n</head>\n<body>\n  \n  <section data-bs-version="5.1" class="menu menu1 cid-uv57SmAmzQ" once="menu" id="menu01-0">\n\t\n\n\t<nav class="navbar navbar-dropdown navbar-expand-lg">\n\t\t<div class="container">\n\t\t\t<div class="navbar-brand">\n\t\t\t\t<span class="navbar-logo">\n\t\t\t\t\t\n\t\t\t\t\t\t<img src="assets/images/bobbybui-1.png" alt="The fur pack logo" style="height: 3.5rem;">\n\t\t\t\t\t\n\t\t\t\t</span>\n\t\t\t\t<span class="navbar-caption-wrap"><a class="navbar-caption text-white text-primary display-4">The fur pack</a></span>\n\t\t\t</div>\n\t\t\t<button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbarSupportedContent" data-bs-target="#navbarSupportedContent" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">\n\t\t\t\t<div class="hamburger">\n\t\t\t\t\t<span></span>\n\t\t\t\t\t<span></span>\n\t\t\t\t\t<span></span>\n\t\t\t\t\t<span></span>\n\t\t\t\t</div>\n\t\t\t</button>\n\t\t\t<div class="collapse navbar-collapse" id="navbarSupportedContent">\n\t\t\t\t<ul class="navbar-nav nav-dropdown" data-app-modern-menu="true"><li class="nav-item">\n\t\t\t\t\t\t<a class="nav-link link text-white display-4" href="https://thefurpack.eu"></a>\n\t\t\t\t\t</li></ul>\n\t\t\t\t\n\t\t\t\t<div class="navbar-buttons mbr-section-btn"><a class="btn btn-white-outline display-4" href="https://hub.thefurpack.eu">Mastodon</a></div>\n\t\t\t</div>\n\t\t</div>\n\t</nav>\n</section>\n\n<section data-bs-version="5.1" class="article07 cid-uv5cY7Ul1w" id="article07-2">\n  \n\n  \n  \n  <div class="container">\n    <div class="row justify-content-center">\n      <div class="card col-md-12 col-lg-10">\n        <div class="card-wrapper">\n          <h3 class="card-title mbr-fonts-style mbr-white mt-3 mb-4 display-2"></h3>\n          <div class="row card-box align-left">\n            <div class="item features-without-image col-12">\n              <div class="item-wrapper">\n                <h4 class="mbr-section-subtitle mbr-fonts-style mb-3 display-2">The fur pack mastodon server</h4>\n                <p class="mbr-text mbr-fonts-style display-7">The fur pack is a mastodon server that is meant to be a safe space for furs that are apart of the LGBTQ+ community. We are a welcoming community to anybody that wants to join. You don\'t have to be a furry or apart of the LGBTQ+ community to join</p>\n              </div>\n            </div>\n            \n            \n            \n          </div>\n          \n        </div>\n      </div>\n    </div>\n  </div>\n</section>\n\n<section class="mbr-section mbr-section--no-padding cid-uv8b0FlqIR" id="witsec-html-block-5">\n\n\n\n\n\n<!-- Place your own code below -->\n<center>\n<blockquote class="mastodon-embed" data-embed-url="https://hub.thefurpack.eu/@snow/113438726807285991/embed" style="background: #FCF8FF; border-radius: 8px; border: 1px solid #C9C4DA; margin: 0; max-width: 540px; min-width: 270px; overflow: hidden; padding: 0;"> <a href="https://hub.thefurpack.eu/@snow/113438726807285991" target="_blank" style="align-items: center; color: #1C1A25; display: flex; flex-direction: column; font-family: system-ui, -apple-system, BlinkMacSystemFont, \'Segoe UI\', Oxygen, Ubuntu, Cantarell, \'Fira Sans\', \'Droid Sans\', \'Helvetica Neue\', Roboto, sans-serif; font-size: 14px; justify-content: center; letter-spacing: 0.25px; line-height: 20px; padding: 24px; text-decoration: none;"> <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="32" height="32" viewBox="0 0 79 75"><path d="M74.7135 16.6043C73.6199 8.54587 66.5351 2.19527 58.1366 0.964691C56.7196 0.756754 51.351 0 38.9148 0H38.822C26.3824 0 23.7135 0.756754 22.2966 0.964691C14.1319 2.16118 6.67571 7.86752 4.86669 16.0214C3.99657 20.0369 3.90371 24.4888 4.06535 28.5726C4.29578 34.4289 4.34049 40.275 4.877 46.1075C5.24791 49.9817 5.89495 53.8251 6.81328 57.6088C8.53288 64.5968 15.4938 70.4122 22.3138 72.7848C29.6155 75.259 37.468 75.6697 44.9919 73.971C45.8196 73.7801 46.6381 73.5586 47.4475 73.3063C49.2737 72.7302 51.4164 72.086 52.9915 70.9542C53.0131 70.9384 53.0308 70.9178 53.0433 70.8942C53.0558 70.8706 53.0628 70.8445 53.0637 70.8179V65.1661C53.0634 65.1412 53.0574 65.1167 53.0462 65.0944C53.035 65.0721 53.0189 65.0525 52.9992 65.0371C52.9794 65.0218 52.9564 65.011 52.9318 65.0056C52.9073 65.0002 52.8819 65.0003 52.8574 65.0059C48.0369 66.1472 43.0971 66.7193 38.141 66.7103C29.6118 66.7103 27.3178 62.6981 26.6609 61.0278C26.1329 59.5842 25.7976 58.0784 25.6636 56.5486C25.6622 56.5229 25.667 56.4973 25.6775 56.4738C25.688 56.4502 25.7039 56.4295 25.724 56.4132C25.7441 56.397 25.7678 56.3856 25.7931 56.3801C25.8185 56.3746 25.8448 56.3751 25.8699 56.3816C30.6101 57.5151 35.4693 58.0873 40.3455 58.086C41.5183 58.086 42.6876 58.086 43.8604 58.0553C48.7647 57.919 53.9339 57.6701 58.7591 56.7361C58.8794 56.7123 58.9998 56.6918 59.103 56.6611C66.7139 55.2124 73.9569 50.665 74.6929 39.1501C74.7204 38.6967 74.7892 34.4016 74.7892 33.9312C74.7926 32.3325 75.3085 22.5901 74.7135 16.6043ZM62.9996 45.3371H54.9966V25.9069C54.9966 21.8163 53.277 19.7302 49.7793 19.7302C45.9343 19.7302 44.0083 22.1981 44.0083 27.0727V37.7082H36.0534V27.0727C36.0534 22.1981 34.124 19.7302 30.279 19.7302C26.8019 19.7302 25.0651 21.8163 25.0617 25.9069V45.3371H17.0656V25.3172C17.0656 21.2266 18.1191 17.9769 20.2262 15.568C22.3998 13.1648 25.2509 11.9308 28.7898 11.9308C32.8859 11.9308 35.9812 13.492 38.0447 16.6111L40.036 19.9245L42.0308 16.6111C44.0943 13.492 47.1896 11.9308 51.2788 11.9308C54.8143 11.9308 57.6654 13.1648 59.8459 15.568C61.9529 17.9746 63.0065 21.2243 63.0065 25.3172L62.9996 45.3371Z" fill="currentColor"></path></svg> <div style="color: #787588; margin-top: 16px;">Post by @<span class="__cf_email__" data-cfemail="2f5c4140586f5b474a495a5d5f4e4c44014a5a">[email&#160;protected]</span></div> <div style="font-weight: 500;">View on Mastodon</div> </a> </blockquote> <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script data-allowed-prefixes="https://hub.thefurpack.eu/" async src="https://hub.thefurpack.eu/embed.js"></script>\n</center>\n<!-- Place your own code above -->\n\n</section>\n\n<section data-bs-version="5.1" class="article07 cid-uv5sFlf89k" id="article07-4">\n  \n\n  \n  \n  <div class="container">\n    <div class="row justify-content-center">\n      <div class="card col-md-12 col-lg-10">\n        <div class="card-wrapper">\n          <h3 class="card-title mbr-fonts-style mbr-white mt-3 mb-4 display-2"></h3>\n          <div class="row card-box align-left">\n            <div class="item features-without-image col-12">\n              <div class="item-wrapper">\n                <h4 class="mbr-section-subtitle mbr-fonts-style mb-3 display-2"></h4>\n                <p class="mbr-text mbr-fonts-style display-7"></p>\n              </div>\n            </div>\n            \n            \n            \n          </div>\n          \n        </div>\n      </div>\n    </div>\n  </div>\n</section><section><a href="https://mobiri.se"></a><a href="https://mobiri.se"></a></section><script src="assets/bootstrap/js/bootstrap.bundle.min.js"></script>  <script src="assets/smoothscroll/smooth-scroll.js"></script>  <script src="assets/ytplayer/index.js"></script>  <script src="assets/dropdown/js/navbar-dropdown.js"></script>  <script src="assets/theme/js/script.js"></script>  \n  \n  \n</body>\n</html>''

External api failed, using internal api instead.
Skipping generation, a tree was already generated for: Weinberg@mastodon.social
Generating a tree for: domino_joyce@ecoevo.social
Skipping generation, a tree was already generated for: vitriolix@mastodon.social
Generating a tree for: jpm@aus.social
Generating a tree for: D_J_Nathanson@esq.social
Skipping generation, a tree was already generated for: blaues_gummibaer@friendica.opensocial.space
Skipping generation, a tree was already generated for: blaues_gummibaer@friendica.opensocial.space
Generating a tree for: thewetmale@aus.social
Generating a tree for: Flegel@moar.cachapa.xyz
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', {'message': 'Unknown API endpoint.', 'code': 'UNKNOWN_API_ENDPOINT', 'id': '2ca3b769-540a-4f08-9dd5-b5a825b6d0f1', 'kind': 'client'})

External api failed, using internal api instead.
Generating a tree for: knizer@toot.boston
Generating a tree for: Corroncio@paquita.masto.host
Generating a tree for: GaiaFinn@mastodontti.fi
Skipping generation, a tree was already generated for: Roboron@im-in.space
Generating a tree for: run_atalanta@beige.party
Generating a tree for: adrian@mastodon.peaceful.social
Skipping generation, a tree was already generated for: Weinberg@mastodon.social
Skipping generation, a tree was already generated for: sebasesrad@paquita.masto.host
Generating a tree for: siquis@paquita.masto.host
Generating a tree for: coolinthegame@social.anoxinon.de
Skipping generation, a tree was already generated for: siquis@paquita.masto.host
Generating a tree for: somcak@beige.party
Generating a tree for: WolvericCatkin@tech.lgbt
Generating a tree for: Adventurer@sfba.social
Skipping generation, a tree was already generated for: RehnSturm256@shota.house
Skipping generation, a tree was already generated for: siquis@paquita.masto.host
Skipping generation, a tree was already generated for: clayrivers@mastodon.world
Generating a tree for: andresmh@hci.social
Generating a tree for: tedfolkman@federate.social
/home/mastodon/.local/lib/python3.9/site-packages/PIL/Image.py:1054: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(
Generating a tree for: fexplorer@procial.tchncs.de
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonUnauthorizedError: ('Mastodon API returned error', 401, 'Unauthorized', {'message': 'Authentication failed. Please ensure your token is correct.', 'code': 'AUTHENTICATION_FAILED', 'id': 'b0a7f5f8-dc2f-4171-b91f-de88ad238e14', 'kind': 'client'})

External api failed, using internal api instead.
Generating a tree for: undefined_variable@mementomori.social
Skipping generation, a tree was already generated for: blaues_gummibaer@friendica.opensocial.space
Generating a tree for: BjornW@mastodon.social
Generating a tree for: JJOtter@cubhub.social
Generating a tree for: wreimers@mastodon.social
Generating a tree for: kat@is.burntout.org
Generating a tree for: acm_redfox@jawns.club
Generating a tree for: fiopv@pipou.academy
Skipping generation, a tree was already generated for: blaues_gummibaer@friendica.opensocial.space
Generating a tree for: daniel_bohrer@chaos.social
Generating a tree for: daniel_bohrer@chaos.social
Generating a tree for: volxfahradler@hessen.social
Generating a tree for: yoyo308@mastodon.online
Generating a tree for: ottost@mastodon.social
Generating a tree for: whangdoodler@piipitin.fi
/home/mastodon/.local/lib/python3.9/site-packages/PIL/Image.py:1054: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(
Generating a tree for: FalconMarkSix@tech.lgbt
Generating a tree for: Ypsilenna@mastodon.social
/home/mastodon/.local/lib/python3.9/site-packages/PIL/Image.py:1054: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(
Generating a tree for: Ypsilenna@vivaldi.net
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'Endpoint not found.')

External api failed, using internal api instead.
Skipping generation, a tree was already generated for: yoyo308@mastodon.online
Generating a tree for: ravi@social.lol
Generating a tree for: vees@epistolary.org
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 154, in <module>
    image = create_image(accounts)
  File "/home/mastodon/mastoes-bots/feditree.py", line 84, in create_image
    with Image.open('feditree/avatar.png') as avatar:
  File "/home/mastodon/.local/lib/python3.9/site-packages/PIL/Image.py", line 3536, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/home/mastodon/mastoes-bots/feditree/avatar.png'

Generating a tree for: fanf42@treehouse.systems
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'Endpoint not found.')

External api failed, using internal api instead.
Generating a tree for: RunRichRun@mastodon.social
Skipping generation, a tree was already generated for: maija@netzsphaere.xyz
Skipping generation, a tree was already generated for: maija@netzsphaere.xyz
Skipping generation, a tree was already generated for: Nenyavie@fedi.lat
Skipping generation, a tree was already generated for: adra@fedi.lat
Generating a tree for: Devils_Rancher@beige.party
Skipping generation, a tree was already generated for: doctormo@floss.social
Generating a tree for: wcbdata@vis.social
Generating a tree for: wcbdata@vis.social
Generating a tree for: Tysonsylvester@chrisduffley.com
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'Endpoint not found.')

External api failed, using internal api instead.
Generating a tree for: averagehousewife@beige.party
Generating a tree for: teruterubozu@toot.wales
Generating a tree for: csett86@kirche.social
Generating a tree for: nrdufour@gardenstate.social
Generating a tree for: Yuvalne@433.world
Generating a tree for: SnowshadowII@beige.party
Generating a tree for: cosmoscalibur@col.social
Generating a tree for: albusnoctes@col.social
Skipping generation, a tree was already generated for: SnowshadowII@beige.party
Skipping generation, a tree was already generated for: spinneria@liberdon.com
Generating a tree for: KarinG@bildung.social
Generating a tree for: PandaChronicle@ohai.social
Generating a tree for: lua@vixen.zone
Skipping generation, a tree was already generated for: PandaChronicle@ohai.social
Generating a tree for: guayabito@mastodon.cr
Generating a tree for: Saltssaltgirl@mas.to
Skipping generation, a tree was already generated for: Saltssaltgirl@mas.to
Generating a tree for: dev_ric@fosstodon.org
Generating a tree for: jasonhowlin@mastodon.social
Generating a tree for: zwolf59661@rubber.social
Generating a tree for: ebi@khiar.net
Generating a tree for: cobalt@awscommunity.social
Generating a tree for: maryfrancis@mstdn.social
Generating a tree for: obot50549535@left-tusk.com
Generating a tree for: nicoguaro@fosstodon.org
Generating a tree for: sauvik@hci.social
Generating a tree for: Saltssaltgirl@mas.to
Generating a tree for: LoganFive@beige.party
Skipping generation, a tree was already generated for: Saltssaltgirl@mas.to
Skipping generation, a tree was already generated for: LoganFive@beige.party
Generating a tree for: bkeegan@hci.social
Skipping generation, a tree was already generated for: Twig@noauthority.social
Generating a tree for: KirstenAnne@mas.to
Generating a tree for: malveus@mastodonsweden.se
Skipping generation, a tree was already generated for: KirstenAnne@mas.to
Generating a tree for: meshya@mas.to
Skipping generation, a tree was already generated for: andresmh@hci.social
Generating a tree for: deirdrebeth@mas.to
Generating a tree for: M0chaCat@is-likely.gay
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonUnauthorizedError: ('Mastodon API returned error', 401, 'Unauthorized', {'message': 'Authentication failed. Please ensure your token is correct.', 'code': 'AUTHENTICATION_FAILED', 'id': 'b0a7f5f8-dc2f-4171-b91f-de88ad238e14', 'kind': 'client'})

External api failed, using internal api instead.
Skipping generation, a tree was already generated for: M0chaCat@is-likely.gay
Generating a tree for: luthien1126@mastodon.social
Generating a tree for: bitchtanten@mastodon.nu
Skipping generation, a tree was already generated for: bitchtanten@mastodon.nu
Generating a tree for: Brandon_Baez@mstdn.mx
Generating a tree for: cadenwolfgang@furry.engineer
Generating a tree for: highergeometer@mathstodon.xyz
Generating a tree for: danjones000@microwords.goodevilgenius.org
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'Endpoint not found.')

External api failed, using internal api instead.
Generating a tree for: jf@ieji.de
Generating a tree for: timtogan@mastodon.social
Generating a tree for: roland@f.haeder.net
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonServerError: ('Mastodon API returned error', 501, 'Not Implemented', 'API endpoint GET api/v1/accounts/lookup?acct=roland%40f.haeder.net is not implemented but might be in the future.')

External api failed, using internal api instead.
Generating a tree for: InnerAlien@mastodon.social
Generating a tree for: NickGates@friendsofdesoto.social
Generating a tree for: aguamielerogpz@newsie.social
Generating a tree for: piidr0@mastodon.social
Generating a tree for: sitaeylo@paquita.masto.host
/home/mastodon/.local/lib/python3.9/site-packages/PIL/Image.py:1054: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(
Generating a tree for: M_el_viejo@lile.cl
Generating a tree for: perigarcia@paquita.masto.host
Skipping generation, a tree was already generated for: M_el_viejo@lile.cl
Generating a tree for: __Knut_@mastodon.online
Generating a tree for: phrawzty@hachyderm.io
Generating a tree for: casuallynoted@casually.cat
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonBadGatewayError: ('Mastodon API returned error', 502, 'Bad Gateway', None)

External api failed, using internal api instead.
Generating a tree for: steph@fedi.steph.tools
Skipping generation, a tree was already generated for: steph@fedi.steph.tools
Generating a tree for: PetraSaarnisto@mastodontti.fi
Skipping generation, a tree was already generated for: barbara2@loma.ml
Generating a tree for: avanc@chaos.social
Generating a tree for: schenklklopfer@chaos.social
Generating a tree for: lukas@social.lukas-schieren.de
Generating a tree for: jeder@miau.jeder.pl
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 139, in <module>
    accounts_ids = get_ordered_accounts_ids(external_account.id, external_api)
  File "/home/mastodon/mastoes-bots/feditree.py", line 29, in get_ordered_accounts_ids
    statuses = _api.account_statuses(account_id, exclude_reblogs=True, max_id=max_id, limit=80)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 189, in account_statuses
    return self.__api_request('GET', url, params)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonUnauthorizedError: ('Mastodon API returned error', 401, 'Unauthorized', 'This method requires an authenticated user')

External api failed, using internal api instead.
Generating a tree for: Makura@fedi.makura.top
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonUnauthorizedError: ('Mastodon API returned error', 401, 'Unauthorized', 'This API requires an authenticated user')

External api failed, using internal api instead.
Generating a tree for: ahoernchen@nrw.social
Generating a tree for: mikoto@akko.wtf
Generating a tree for: smam@halcyon-is.land
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'Endpoint not found.')

External api failed, using internal api instead.
Generating a tree for: frank@moessingen.social
Skipping generation, a tree was already generated for: PetraSaarnisto@mastodontti.fi
Skipping generation, a tree was already generated for: Makura@fedi.makura.top
Generating a tree for: igwigg@mk.igwigg.space
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonUnauthorizedError: ('Mastodon API returned error', 401, 'Unauthorized', 'Unauthorized')

External api failed, using internal api instead.
Skipping generation, a tree was already generated for: ahoernchen@nrw.social
Generating a tree for: RafiX@outerheaven.club
Generating a tree for: kansi@halcyon-is.land
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'Endpoint not found.')

External api failed, using internal api instead.
Generating a tree for: citizenk4te@nrw.social
Skipping generation, a tree was already generated for: ahoernchen@nrw.social
Generating a tree for: AmbrosTheGreat@mastodon.la
Skipping generation, a tree was already generated for: Invisibol@mastodon.social
Generating a tree for: lazarus@fosstodon.org
Generating a tree for: mike@fuerth.social
Skipping generation, a tree was already generated for: cheri@snug.moe
Generating a tree for: aismallard@woem.space
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 154, in <module>
    image = create_image(accounts)
  File "/home/mastodon/mastoes-bots/feditree.py", line 84, in create_image
    with Image.open('feditree/avatar.png') as avatar:
  File "/home/mastodon/.local/lib/python3.9/site-packages/PIL/Image.py", line 3536, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/home/mastodon/mastoes-bots/feditree/avatar.png'

Generating a tree for: Yewa@troet.cafe
Generating a tree for: frubizym@nrw.social
Generating a tree for: rick@a.n0id.space
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonUnauthorizedError: ('Mastodon API returned error', 401, 'Unauthorized', 'This API requires an authenticated user')

External api failed, using internal api instead.
Skipping generation, a tree was already generated for: rick@a.n0id.space
Skipping generation, a tree was already generated for: rick@a.n0id.space
Generating a tree for: rodirik@norden.social
Generating a tree for: escuco@norden.social
Skipping generation, a tree was already generated for: Melissabeartrix@hugz.online
Generating a tree for: hoppaz@social.tchncs.de
Generating a tree for: eptf@octodon.social
Generating a tree for: shezza_t@mastodon.ie
Generating a tree for: Pixdigit@layer8.space
Generating a tree for: ley__de__murphy@mastorol.es
Generating a tree for: ErikUden@mastodon.de
Generating a tree for: annakansalais@eliitin-some.fi
Skipping generation, a tree was already generated for: annakansalais@eliitin-some.fi
Skipping generation, a tree was already generated for: henrik@eliitin-some.fi
Generating a tree for: blub@ak.kawen.space
Skipping generation, a tree was already generated for: lordsplodge@brettspiel.space
Generating a tree for: skajmer@pol.social
Generating a tree for: hpiirai@piipitin.fi
Generating a tree for: puhuri@mastodon.social
Generating a tree for: blumlaut@hounds.online
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonUnauthorizedError: ('Mastodon API returned error', 401, 'Unauthorized', {'message': 'Authentication failed. Please ensure your token is correct.', 'code': 'AUTHENTICATION_FAILED', 'id': 'b0a7f5f8-dc2f-4171-b91f-de88ad238e14', 'kind': 'client'})

External api failed, using internal api instead.
Generating a tree for: DwarfX@mastodon.ml
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 160, in <module>
    api.status_post(status, media_ids=image, visibility="unlisted", in_reply_to_id=notification.status.id, language=lang)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/statuses.py", line 253, in status_post
    return self.__status_internal(
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/statuses.py", line 187, in __status_internal
    return self.__api_request('POST', '/api/v1/statuses', params, headers=headers, use_json=use_json)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'La publicación a la que intentas responder no existe.')

Generating a tree for: DwarfX@mastodon.ml
Generating a tree for: cardi@chaos.social
Generating a tree for: rochelimit@tilde.zone
Generating a tree for: ley__de__murphy@mastorol.es
Generating a tree for: miicat_47@mastodon.miicat.eu
Generating a tree for: 23Sonics@evilfoundry.net
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonUnauthorizedError: ('Mastodon API returned error', 401, 'Unauthorized', {'message': 'Authentication failed. Please ensure your token is correct.', 'code': 'AUTHENTICATION_FAILED', 'id': 'b0a7f5f8-dc2f-4171-b91f-de88ad238e14', 'kind': 'client'})

External api failed, using internal api instead.
Generating a tree for: jagesta@eliitin-some.fi
Generating a tree for: dirk_wagner_@norden.social
Generating a tree for: lukadjo@app.wafrn.net
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'Endpoint not found.')

External api failed, using internal api instead.
Skipping generation, a tree was already generated for: yassie_j@labyrinth.zone
Skipping generation, a tree was already generated for: adhdeanasl@beige.party
Generating a tree for: SemAntiKast@openbiblio.social
Generating a tree for: flandrescarlet@uwu.social
Generating a tree for: mehr@mastodon.social
Skipping generation, a tree was already generated for: Erpel@hai.z0ne.social
Generating a tree for: Erpel@hai.z0ne.social
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonUnauthorizedError: ('Mastodon API returned error', 401, 'Unauthorized', {'message': 'Authentication failed. Please ensure your token is correct.', 'code': 'AUTHENTICATION_FAILED', 'id': 'b0a7f5f8-dc2f-4171-b91f-de88ad238e14', 'kind': 'client'})

External api failed, using internal api instead.
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 122, in <module>
    if check_removal(notification, api): continue
  File "/home/mastodon/mastoes-bots/feditree.py", line 105, in check_removal
    status_to_delete = api.status(notification.status.in_reply_to_id)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/statuses.py", line 27, in status
    return self.__api_request('GET', url)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'Record not found')

Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 122, in <module>
    if check_removal(notification, api): continue
  File "/home/mastodon/mastoes-bots/feditree.py", line 105, in check_removal
    status_to_delete = api.status(notification.status.in_reply_to_id)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/statuses.py", line 27, in status
    return self.__api_request('GET', url)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'Record not found')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 166, in <module>
    status += _("An error ocurred. I have probably reached my posting limit. Please try again in an hour or contact my creator if I keep failing.")
NameError: name '_' is not defined
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 124, in <module>
    if check_removal(notification, api): continue
  File "/home/mastodon/mastoes-bots/feditree.py", line 105, in check_removal
    status_to_delete = api.status(notification.status.in_reply_to_id)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/statuses.py", line 27, in status
    return self.__api_request('GET', url)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'Record not found')

Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 124, in <module>
    if check_removal(notification, api): continue
  File "/home/mastodon/mastoes-bots/feditree.py", line 105, in check_removal
    status_to_delete = api.status(notification.status.in_reply_to_id)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/statuses.py", line 27, in status
    return self.__api_request('GET', url)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'Record not found')

Generating a tree for: andor@pierdelacabeza.com
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'Endpoint not found.')

External api failed, using internal api instead.
Generating a tree for: pijusmagnificus@gotosocial.gundan.es
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 138, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonUnauthorizedError: ('Mastodon API returned error', 401, 'Unauthorized', 'Unauthorized: token not supplied')

External api failed, using internal api instead.
Skipping generation, a tree was already generated for: andor@pierdelacabeza.com
Skipping generation, a tree was already generated for: Gauss@furry.engineer
Generating a tree for: hiogepo@tuiter.rocks
Skipping generation, a tree was already generated for: jeremystartm@fly.staropensource.de
Skipping generation, a tree was already generated for: jeremystartm@fly.staropensource.de
Generating a tree for: ScottStarkey@hoosier.social
Generating a tree for: phranck@chaos.social
Generating a tree for: vees@epistolary.org
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 158, in <module>
    image = create_image(accounts)
  File "/home/mastodon/mastoes-bots/feditree.py", line 84, in create_image
    with Image.open('feditree/avatar.png') as avatar:
  File "/home/mastodon/.local/lib/python3.9/site-packages/PIL/Image.py", line 3536, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/home/mastodon/mastoes-bots/feditree/avatar.png'

Generating a tree for: Mark@weird.autos
Skipping generation, a tree was already generated for: Mark@weird.autos
Generating a tree for: vgarzareyna@mstdn.mx
Generating a tree for: Basmitharts@weird.autos
Skipping generation, a tree was already generated for: Basmitharts@weird.autos
Skipping generation, a tree was already generated for: regendans@toot.community
Skipping generation, a tree was already generated for: clayrivers@mastodon.world
Skipping generation, a tree was already generated for: revndm@tech.lgbt
Generating a tree for: Amouei@khiar.net
Generating a tree for: rmounce@mastodon.social
Generating a tree for: eike@novoa.nagoya
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 142, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', {'message': 'Unknown API endpoint.', 'code': 'UNKNOWN_API_ENDPOINT', 'id': '2ca3b769-540a-4f08-9dd5-b5a825b6d0f1', 'kind': 'client'})

External api failed, using internal api instead.
Skipping generation, a tree was already generated for: chinmay@treehouse.systems
Generating a tree for: chinmay@treehouse.systems
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 142, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'Endpoint not found.')

External api failed, using internal api instead.
Generating a tree for: FlanFlinger@mastodon.social
Generating a tree for: BL_DigiSchol@techhub.social
Generating a tree for: ideimos
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 139, in <module>
    external_domain = notification.account.acct.split("@")[1]
IndexError: list index out of range

External api failed, using internal api instead.
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 139, in <module>
    external_domain = notification.account.acct.split("@")[1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 148, in <module>
    if(status_domain != domain):
NameError: name 'status_domain' is not defined

Generating a tree for: Dunkel217@mastodon.social
Generating a tree for: BlueDot@left-tusk.com
Generating a tree for: aismallard@woem.space
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 158, in <module>
    image = create_image(accounts)
  File "/home/mastodon/mastoes-bots/feditree.py", line 84, in create_image
    with Image.open('feditree/avatar.png') as avatar:
  File "/home/mastodon/.local/lib/python3.9/site-packages/PIL/Image.py", line 3536, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/home/mastodon/mastoes-bots/feditree/avatar.png'

Generating a tree for: fdeitylink@types.pl
Generating a tree for: wheeljack@retro.pizza
Generating a tree for: wheeljack@weird.autos
Generating a tree for: qcoolka@101010.pl
Generating a tree for: farbel@mas.to
Generating a tree for: Carnivius@masto.ai
Generating a tree for: James@woof.group
Generating a tree for: lily@homestead.social
Generating a tree for: debacle@framapiaf.org
Generating a tree for: pixelgordo
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 139, in <module>
    external_domain = notification.account.acct.split("@")[1]
IndexError: list index out of range

External api failed, using internal api instead.
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 139, in <module>
    external_domain = notification.account.acct.split("@")[1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 148, in <module>
    if(status_domain != domain):
NameError: name 'status_domain' is not defined

Generating a tree for: kowantures@digitalcourage.social
Generating a tree for: EVDHmn@ecoevo.social
Skipping generation, a tree was already generated for: EVDHmn@ecoevo.social
Skipping generation, a tree was already generated for: EVDHmn@ecoevo.social
Generating a tree for: mturczynowicz@pol.social
Generating a tree for: rober
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 140, in <module>
    external_domain = notification.account.acct.split("@")[1]
IndexError: list index out of range

External api failed, using internal api instead.
Generating a tree for: ideimos
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 140, in <module>
    external_domain = notification.account.acct.split("@")[1]
IndexError: list index out of range

External api failed, using internal api instead.
Generating a tree for: manu@paquita.masto.host
Generating a tree for: manchapod@xerrem.xyz
Skipping generation, a tree was already generated for: manchapod@xerrem.xyz
Generating a tree for: yurnidiot@mstdn.social
Generating a tree for: pixelpusher220@dmv.community
Generating a tree for: currentbias@zeroes.ca
Skipping generation, a tree was already generated for: FlockOfCats@famichiki.jp
Generating a tree for: jstatepost@mstdn.social
Generating a tree for: pixelgordo
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 140, in <module>
    external_domain = notification.account.acct.split("@")[1]
IndexError: list index out of range

External api failed, using internal api instead.
Generating a tree for: Aussiemandias@mastodon.social
Generating a tree for: pork_soda@friendsofdesoto.social
Generating a tree for: TerpomoDekUnu@esperanto.masto.host
Generating a tree for: pb4000@infosec.exchange
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 159, in <module>
    image = create_image(accounts)
  File "/home/mastodon/mastoes-bots/feditree.py", line 84, in create_image
    with Image.open('feditree/avatar.png') as avatar:
  File "/home/mastodon/.local/lib/python3.9/site-packages/PIL/Image.py", line 3536, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/home/mastodon/mastoes-bots/feditree/avatar.png'

Generating a tree for: isleofmandan@mstdn.social
Generating a tree for: paulox@fosstodon.org
Generating a tree for: paulox@fosstodon.org
Generating a tree for: tommi@pan.rent
Generating a tree for: Hipska@mastodon-belgium.be
Generating a tree for: slims@famichiki.jp
Generating a tree for: amy@types.pl
Generating a tree for: stellarskylark@solarpunk.moe
Generating a tree for: anarcoaceituna@mastodon.social
Generating a tree for: dagger@chaos.social
Generating a tree for: jmaris@eupolicy.social
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 144, in <module>
    accounts_ids = get_ordered_accounts_ids(external_account.id, external_api)
  File "/home/mastodon/mastoes-bots/feditree.py", line 29, in get_ordered_accounts_ids
    statuses = _api.account_statuses(account_id, exclude_reblogs=True, max_id=max_id, limit=80)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 189, in account_statuses
    return self.__api_request('GET', url, params)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonGatewayTimeoutError: ('Mastodon API returned error', 504, 'Gateway Time-out', None)

External api failed, using internal api instead.
Generating a tree for: neffscape@fosstodon.org
Generating a tree for: neffscape@fosstodon.org
Generating a tree for: CodenameTim@fosstodon.org
Skipping generation, a tree was already generated for: LLOBU
Generating a tree for: floppyplopper@todon.nl
Generating a tree for: kei@functional.cafe
Generating a tree for: pb4000@infosec.exchange
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 159, in <module>
    image = create_image(accounts)
  File "/home/mastodon/mastoes-bots/feditree.py", line 84, in create_image
    with Image.open('feditree/avatar.png') as avatar:
  File "/home/mastodon/.local/lib/python3.9/site-packages/PIL/Image.py", line 3536, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/home/mastodon/mastoes-bots/feditree/avatar.png'

Generating a tree for: globcoco@mamot.fr
Generating a tree for: acousson@sciences.re
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 143, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'Endpoint not found.')

External api failed, using internal api instead.
Generating a tree for: astrocat@mas.to
Generating a tree for: dyniec@tech.lgbt
Generating a tree for: EOHenning@esperanto.masto.host
Generating a tree for: LLOBU
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 140, in <module>
    external_domain = notification.account.acct.split("@")[1]
IndexError: list index out of range

External api failed, using internal api instead.
Generating a tree for: globcoco@mamot.fr
Generating a tree for: Mawoka@mastodon.online
Generating a tree for: ana@tuiter.rocks
Generating a tree for: chiwy@kolektiva.social
Generating a tree for: Aficionadisima
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 140, in <module>
    external_domain = notification.account.acct.split("@")[1]
IndexError: list index out of range

External api failed, using internal api instead.
Generating a tree for: peter_winninger@bonn.social
Skipping generation, a tree was already generated for: debacle@framapiaf.org
Generating a tree for: echedellelr@fearness.org
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 143, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonUnauthorizedError: ('Mastodon API returned error', 401, 'Unauthorized', {'message': 'Authentication failed. Please ensure your token is correct.', 'code': 'AUTHENTICATION_FAILED', 'id': 'b0a7f5f8-dc2f-4171-b91f-de88ad238e14', 'kind': 'client'})

External api failed, using internal api instead.
Generating a tree for: gameplayer@fearness.org
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 143, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonUnauthorizedError: ('Mastodon API returned error', 401, 'Unauthorized', {'message': 'Authentication failed. Please ensure your token is correct.', 'code': 'AUTHENTICATION_FAILED', 'id': 'b0a7f5f8-dc2f-4171-b91f-de88ad238e14', 'kind': 'client'})

External api failed, using internal api instead.
Generating a tree for: gameplayer@mrrp.chimmie.k.vu
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 143, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonUnauthorizedError: ('Mastodon API returned error', 401, 'Unauthorized', {'message': 'Authentication failed. Please ensure your token is correct.', 'code': 'AUTHENTICATION_FAILED', 'id': 'b0a7f5f8-dc2f-4171-b91f-de88ad238e14', 'kind': 'client'})

External api failed, using internal api instead.
Generating a tree for: bengillam@mastodon.social
Skipping generation, a tree was already generated for: simonharper@mastodon.social
Skipping generation, a tree was already generated for: onecreativecat@mastodon.art
Generating a tree for: ff16e04363da999a0645281d7bcc8ae23131e5708e5e3c32631b97c8767df70b@mostr.pub
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 143, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'Endpoint not found.')

External api failed, using internal api instead.
Generating a tree for: stedi@mementomori.social
Skipping generation, a tree was already generated for: transbutterflyqueen@kitsunes.club
Generating a tree for: transbutterflyqueen@kitsunes.club
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 143, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonUnauthorizedError: ('Mastodon API returned error', 401, 'Unauthorized', {'message': 'Authentication failed. Please ensure your token is correct.', 'code': 'AUTHENTICATION_FAILED', 'id': 'b0a7f5f8-dc2f-4171-b91f-de88ad238e14', 'kind': 'client'})

External api failed, using internal api instead.
Skipping generation, a tree was already generated for: asoukes@talk.marq42.xyz
Skipping generation, a tree was already generated for: transbutterflyqueen@kitsunes.club
Generating a tree for: aFard@techhub.social
Skipping generation, a tree was already generated for: coloco@mstdn.social
Skipping generation, a tree was already generated for: coloco@mstdn.social
Generating a tree for: fiskben3@mastodon.nu
/home/mastodon/.local/lib/python3.9/site-packages/PIL/Image.py:1054: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(
Generating a tree for: piuland@mastodon.green
Generating a tree for: Disruptivo@mastodon.social
Generating a tree for: courtcan@mastodon.social
Generating a tree for: GoatRoper@mastodon.social
Generating a tree for: scottmiller42@mstdn.social
Skipping generation, a tree was already generated for: GoatRoper@mastodon.social
Skipping generation, a tree was already generated for: jstatepost@mstdn.social
Skipping generation, a tree was already generated for: Melissabeartrix@hugz.online
Skipping generation, a tree was already generated for: courtcan@mastodon.social
Generating a tree for: SeaFury@aus.social
Generating a tree for: GoatRoper@mastodon.social
Generating a tree for: ampersine@mastodon.online
Generating a tree for: Ricardus@mastodon.sdf.org
Skipping generation, a tree was already generated for: GoatRoper@mastodon.social
Generating a tree for: tootadyneLPD@mastodon.social
Generating a tree for: vftdan@mastodon.ml
Generating a tree for: martindrogat@hessen.social
Generating a tree for: categulario@mstdn.mx
Skipping generation, a tree was already generated for: fernand0@mastodon.social
Generating a tree for: _dmh@mastodon.social
Generating a tree for: cesariux23@mstdn.mx
Generating a tree for: ludv@fosstodon.org
Generating a tree for: max@mk.noob.quest
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 143, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonUnauthorizedError: ('Mastodon API returned error', 401, 'Unauthorized', {'message': 'Authentication failed. Please ensure your token is correct.', 'code': 'AUTHENTICATION_FAILED', 'id': 'b0a7f5f8-dc2f-4171-b91f-de88ad238e14', 'kind': 'client'})

External api failed, using internal api instead.
Generating a tree for: laprice@beige.party
Generating a tree for: arichtman@eigenmagic.net
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 159, in <module>
    image = create_image(accounts)
  File "/home/mastodon/mastoes-bots/feditree.py", line 84, in create_image
    with Image.open('feditree/avatar.png') as avatar:
  File "/home/mastodon/.local/lib/python3.9/site-packages/PIL/Image.py", line 3536, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/home/mastodon/mastoes-bots/feditree/avatar.png'

Generating a tree for: UnclePJ@beige.party
Generating a tree for: bacteriano@mstdn.mx
Skipping generation, a tree was already generated for: thedoctor@polymaths.social
Generating a tree for: tim@social.techn1k.de
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 143, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonAPIError: ('Mastodon API returned error', 403, 'Forbidden', 'This resource requires authentication.')

External api failed, using internal api instead.
Generating a tree for: eaganj@hci.social
Generating a tree for: mujtablue@khiar.net
Skipping generation, a tree was already generated for: sneexy@booping.synth.download
Generating a tree for: senil888@furry.engineer
Generating a tree for: stefenauris@furry.engineer
Generating a tree for: mono@antisocial.lamadriguera.cloud
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 143, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonUnauthorizedError: ('Mastodon API returned error', 401, 'Unauthorized', 'Unauthorized: token not supplied')

External api failed, using internal api instead.
Generating a tree for: Lu@ieji.de
Skipping generation, a tree was already generated for: ink_ase@mas.to
Generating a tree for: NatalyMillan@mastodon.social
Skipping generation, a tree was already generated for: NatalyMillan@mastodon.social
Generating a tree for: violenteastcoastcity@mastodon.social
Generating a tree for: lopezsanchez@mas.to
Skipping generation, a tree was already generated for: spud@is-hardly.online
Generating a tree for: katzentratschen@mastodon.social
Generating a tree for: kolombiken@front-end.social
Generating a tree for: mhabedi@persadon.com
Generating a tree for: csolisr@hub.azkware.net
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 143, in <module>
    external_account = external_api.account_lookup(notification.account.acct)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/accounts.py", line 285, in account_lookup
    return self.__api_request('GET', '/api/v1/accounts/lookup', self.__generate_params(locals()))
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonUnauthorizedError: ('Mastodon API returned error', 401, 'Unauthorized', None)

External api failed, using internal api instead.
Generating a tree for: NimaZakariaei@mas.to
Generating a tree for: albertcuesta@mastodont.cat
Generating a tree for: quimsilvestre@mastodont.cat
Generating a tree for: ssanf01@mastodon.social
Generating a tree for: ceskfreixas@mastodont.cat
Generating a tree for: pb4000@infosec.exchange
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 159, in <module>
    image = create_image(accounts)
  File "/home/mastodon/mastoes-bots/feditree.py", line 84, in create_image
    with Image.open('feditree/avatar.png') as avatar:
  File "/home/mastodon/.local/lib/python3.9/site-packages/PIL/Image.py", line 3536, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/home/mastodon/mastoes-bots/feditree/avatar.png'

Generating a tree for: folfdk@helvede.net
Generating a tree for: tokeriis@helvede.net
Generating a tree for: infonauten@helvede.net
Generating a tree for: SorenMRiis@helvede.net
Generating a tree for: thriveth@astrodon.social
Skipping generation, a tree was already generated for: wcbdata@vis.social
Generating a tree for: janeadams@datavis.social
Skipping generation, a tree was already generated for: ai6yr@m.ai6yr.org
Generating a tree for: evn@gamedev.lgbt
Skipping generation, a tree was already generated for: malveus@mastodonsweden.se
Generating a tree for: Karolina@mastodonsweden.se
Generating a tree for: temptoetiam@eldritch.cafe
Generating a tree for: JulMorgane@piaille.fr
Generating a tree for: jwarlander@mastodon.nu
Generating a tree for: AlexUnder@eldritch.cafe
Traceback (most recent call last):
  File "/home/mastodon/mastoes-bots/feditree.py", line 165, in <module>
    api.status_post(status, media_ids=image, visibility="unlisted", in_reply_to_id=notification.status.id, language=lang)
  File "/home/mastodon/.local/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/statuses.py", line 253, in status_post
    return self.__status_internal(
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/statuses.py", line 187, in __status_internal
    return self.__api_request('POST', '/api/v1/statuses', params, headers=headers, use_json=use_json)
  File "/home/mastodon/.local/lib/python3.9/site-packages/mastodon/internals.py", line 299, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.errors.MastodonNotFoundError: ('Mastodon API returned error', 404, 'Not Found', 'La publicación a la que intentas responder no existe.')

Generating a tree for: AlexUnder@eldritch.cafe
Generating a tree for: mc@piaille.fr
Generating a tree for: tisaac@piaille.fr
Generating a tree for: julbriman@piaille.fr
Generating a tree for: ploum@mamot.fr
Generating a tree for: ludomire@tooting.ch
Generating a tree for: pvheditions@lire.im
Skipping generation, a tree was already generated for: PhieLaidMignon@cornichon.me
